import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import styles from "../../styles/Company.module.css";
import { protectRoute } from "../../HOC/protectedRoute";

export async function getStaticProps(context) {
	try {
		const { id_recruiter } = context.params;
		const response = await axios({
			method: "GET",
			url: `${process.env.NEXT_PUBLIC_BACKEND_URL}/recruiter/${id_recruiter}`,
		});
		return {
			props: {
				data: response.data.data.rows,
			},
			revalidate: 10,
			notFound: false,
		};
	} catch (error) {
		return {
			props: {
				data: null,
			},
			revalidate: 10, // 60 second
			notFound: true,
		};
	}
}

// Generates `/posts/1` and `/posts/2`
export async function getStaticPaths() {
	const response = await axios({
		method: "GET",
		url: `${process.env.NEXT_PUBLIC_BACKEND_URL}/recruiter`,
	});
	// console.log(response.data);

	const paths = response.data.data.rows.map((item) => {
		return { params: { id_recruiter: item.id_recruiter.toString() } };
	});
	return {
		paths,
		fallback: "blocking", // can also be true or 'blocking'
	};
}

const CompanyProfile = (props) => {
	const data = props.data;
	// console.log(data.length);
	return (
		<>
			<Head>
				<title>Profile</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/Logo.png" />
			</Head>
			<div className="container-fluid row">
				<div>
					<div className="d-flex justify-content-center align-items-center text-center mx-auto">
						<div className={`position-absolute ${styles.margin}`}>
							<Image
								src={
									data.length === 1
										? `${data[0].profile_pic.split("|&&|")[0]}`
										: "/"
								}
								width={150}
								height={150}
								alt=""
								className={`${styles.picture} `}
							/>
							<h1>{data.length === 1 ? data[0].perusahaan : ""}</h1>
							<p>{data.length === 1 ? data[0].bidang : ""}</p>
							<p className={`${styles.text}`}>
								{data.length === 1 ? data[0].kota : ""}
							</p>
							<p className={`${styles.text}`}>
								{data.length === 1 ? data[0].description : ""}
							</p>
							<Link href={`/company/editcompany/${data[0].id_recruiter}`}>
								<button className={`${styles.buttons} col-12 mb-4`}>
									Edit Profile
								</button>
							</Link>
							<p className={`${styles.text}`}>
								{data.length === 1 ? data[0].email : ""}
							</p>
							<p className={`${styles.text}`}>
								{data.length === 1 ? data[0].instagram : ""}
							</p>
							<p className={`${styles.text}`}>
								{data.length === 1 ? data[0].phone : ""}
							</p>
						</div>
					</div>
					<div className={`col-10 mx-auto my-4`}>
						<div
							className={`${styles.bgUngu} ${styles.border1} ${styles.block}`}></div>
						<div
							className={`${styles.bgAbu} ${styles.border2} ${styles.block}`}></div>
					</div>
				</div>
			</div>
		</>
	);
};

CompanyProfile.navbar = "L2";
export default protectRoute(CompanyProfile);
