import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import styles from "../../styles/Hire.module.css";
import { protectRoute } from "../../HOC/protectedRoute";

const Hire = () => {
	const [data, setData] = useState([]);

	const router = useRouter();
	const { id_user } = router.query;

	useEffect(() => {
		if (id_user) {
			axios
				.get(`${process.env.NEXT_PUBLIC_BACKEND_URL}/user/${id_user}`)
				.then((response) => {
					setData(response.data.data.rows);
				})
				.catch((error) => {
					console.log(error);
				});
		}
	}, [router.isReady, id_user]);

	return (
		<>
			<Head>
				<title>{data.length === 1 ? data[0].names : "Next App"}</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/Logo.png" />
			</Head>
			<div className={`container-fluid row ${styles.bg}`}>
				<div className={`position-absolute translate-middle-y ps-5 my-5`}>
					<div className="row col-11 ms-5 position-absolute my-5">
						<div className="col-md-3 col-12 me-4 position-relative">
							<section className={`${styles.cards} p-3`}>
								<Image
									src={
										data.length === 1
											? `${data[0].profile_pic.split("|&&|")[0]}`
											: "/#"
									}
									width={135}
									height={135}
									className={`mx-auto d-block my-3 ${styles.profileImg}`}
									priority={true}
									alt={`Profile picture`}
								/>
								<h4>{data.length === 1 ? data[0].names : ""}</h4>
								<p>{data.length === 1 ? data[0].job_desc : ""}</p>
								<div className="row">
									<Image
										src="/map.png"
										width={14}
										height={14}
										className="col-auto"
										alt="Domisili"
									/>
									<p
										className={`col-auto ${styles.text} ${styles.textAddress}`}>
										{data.length === 1 ? data[0].domisili : ""}
									</p>
								</div>
								<p className={`${styles.text}`}>
									{data.length === 1 ? data[0].tempat_kerja : ""}
								</p>
								<p className={`${styles.text}`}>
									{data.length === 1 ? data[0].description : ""}
								</p>
								<div className="my-3">
									<h4>Skill</h4>
									{data.length === 1 ? (
										data[0].skill !== null ? (
											data[0].skill.split(",").map((item, index) => (
												<button
													key={index}
													className={`col-4 m-1 p-1 ${styles.btnSkills}`}>
													{item}
												</button>
											))
										) : (
											<h3>No skill</h3>
										)
									) : (
										""
									)}
								</div>
								<div className="row">
									<Image
										src="/mail.png"
										width={18}
										height={18}
										className="col-auto"
										alt=""
									/>
									<p
										className={`col-auto ${styles.text} ${styles.textAddress}`}>
										{data.length === 1 ? data[0].email : ""}
									</p>
								</div>
								<div className="row">
									<Image
										src="/instagram.png"
										width={18}
										height={18}
										className="col-auto"
										alt=""
									/>
									<p
										className={`col-auto ${styles.text} ${styles.textAddress}`}>
										@louistomlinson
									</p>
								</div>
							</section>
						</div>
						<div className="position-relative col-8 ms-4">
							<section className={`mb-3`}>
								<div className="mb-5">
									<h3>Hubungi {data.names}</h3>
									<p>
										Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
										euismod ipsum et dui rhoncus auctor.
									</p>
								</div>
								<form className="col-12">
									<div className="mb-3">
										<label htmlFor="project" className={`form-label`}>
											Tujuan tentang pesan ini
										</label>
										<select
											className={`form-select ${styles.input}`}
											id="project">
											<option defaultValue="">Project</option>
											<option value="1">One</option>
											<option value="2">Two</option>
											<option value="3">Three</option>
										</select>
									</div>
									<div className="mb-4">
										<label htmlFor="nameInput" className={`form-label`}>
											Nama Lengkap
										</label>
										<input
											type="text"
											className={`form-control ${styles.input}`}
											id="nameInput"
											placeholder="Masukan nama lengkap"
										/>
									</div>
									<div className="mb-4">
										<label htmlFor="emailInput" className={`form-label`}>
											Email
										</label>
										<input
											type="text"
											className={`form-control ${styles.input}`}
											id="emailInput"
											placeholder="Masukan nama email"
										/>
									</div>
									<div className="mb-4">
										<label htmlFor="phoneInput" className={`form-label`}>
											No handphone
										</label>
										<input
											type="text"
											className={`form-control ${styles.input}`}
											id="phoneInput"
											placeholder="Masukan no handphone"
										/>
									</div>
									<div className="mb-4">
										<label htmlFor="tempatKerja" className={`form-label`}>
											Deskripsi
										</label>
										<textarea
											type="text"
											className={`form-control ${styles.textarea}`}
											id="textarea"
											placeholder="Masukkan deskripsi singkat"
										/>
									</div>
									<button className={`${styles.btnSkill} col-12`} type="submit">
										Hire
									</button>
								</form>
							</section>
						</div>
					</div>
				</div>
			</div>
			<div className={`${styles.bgPutih}`}></div>
		</>
	);
};

Hire.navbar = "L2";

export default protectRoute(Hire);
